baseURL = "https://rm3l.org/"
disablePathToLower = true
languageCode = "en-us"
title = "Armel Soro's blog"
theme = "ascii-press"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
