apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{RESOURCE_NAME}}
spec:
  rules:
    - host: "{{DOMAIN_NAME}}"
      http:
        paths:
          - path: "{{ ACCESS_PATH }}"
            pathType: Prefix
            backend:
              service:
                name: {{RESOURCE_NAME}} 
                port:
                  number: {{CONTAINER_PORT}}
