apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{RESOURCE_NAME}}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    kubernetes.io/ingress.class: "{{DEPLOY_INGRESS_CLASS}}"
spec:
  # Looks like Traefik 2.5 does not support spec.ingressClassName =>
  # had to use the "kubernetes.io/ingress.class" annotation instead
  # ingressClassName: traefik
  tls:
  - hosts:
    - {{DOMAIN_NAME}}
    secretName: "{{RESOURCE_NAME}}-ingress-certificate-secret"

  rules:
    - host: "{{DOMAIN_NAME}}"
      http:
        paths:
          - path: "{{ ACCESS_PATH }}"
            pathType: Prefix
            backend:
              service:
                name: {{RESOURCE_NAME}} 
                port:
                  number: {{CONTAINER_PORT}}
