name: Pull Request Preview

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, closed]
    branches: [ main ]

defaults:
  run:
    shell: bash

env:
  ODO_DISABLE_TELEMETRY: "true"
  PODMAN_CMD: "docker"
  PR_NUMBER: ${{ github.event.number }}

jobs:
  deploy-preview:
    if: ${{ github.event.pull_request.state == 'open' }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v1

      - run: |
          yq w -i devfile.yaml metadata.name "rm3l-org-pr-${{ env.PR_NUMBER }}"

      - name: Generate Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 400 ~/.kube/config

      - name: Create and set namespace
        run: |
          if odo list namespaces | grep "pr-${PR_NUMBER}"; then
            echo "Namespace pr-${PR_NUMBER} already exists."
          else
            echo "Namespace pr-${PR_NUMBER} *not* found => creating it."
            odo create namespace "pr-${PR_NUMBER}"
          fi
          odo set namespace "pr-${PR_NUMBER}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Deploy locally with odo
        run: |
          odo deploy -v 4 \
            --var ACCESS_PATH=/pr-"${PR_NUMBER}" \
            --var CONTAINER_IMAGE=docker.io/rm3l/rm3l.org \
            --var CONTAINER_IMAGE_TAG=pr-"${PR_NUMBER}" \
            --var DOMAIN_NAME=website-preview.rm3l.org

      - name: Test access
        run: |
          wget --no-check-certificate \
            --tries=20 \
            --retry-on-host-error \
            --retry-on-http-error=404,503 \
            -S \
            -O - \
            "https://website-preview.rm3l.org/pr-${PR_NUMBER}" || exit 1

      - name: Add PR comment with preview URL
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'PR Preview: https://website-preview.rm3l.org/pr-${{ env.PR_NUMBER }}'
          comment_includes: 'PR Preview: '
          pr_number: ${{ env.PR_NUMBER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reactions: rocket

  delete_resources_for_pr:
    if: ${{ github.event.pull_request.state == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v1

      - name: Generate Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 400 ~/.kube/config

      - name: Delete component
        run: |
          odo delete component \
            --namespace "pr-${PR_NUMBER}" \
            --name "rm3l-org-pr-${PR_NUMBER}" \
            --force \
            --wait \
          || true

      - name: Delete namespace
        if: ${{ always() }}
        run: |
          odo delete namespace "pr-${PR_NUMBER}" \
            --wait \
            --force \
          || true
